services:
  # Minecraft Server
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft-multiagent
    ports:
      - "25565:25565"
      - "25575:25575"  # RCON port
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "1.21"
      MEMORY: "2G"
      SPAWN_PROTECTION: 0
      MAX_PLAYERS: 10
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: 25575
      ONLINE_MODE: "false"  # Allow offline mode for bots
      DIFFICULTY: "peaceful"
      GAMEMODE: "creative"
      SPAWN_MONSTERS: "false"
      SPAWN_ANIMALS: "true"
      VIEW_DISTANCE: 10
      # Logging verbosity options
      DEBUG: "TRUE"
      ENABLE_ROLLING_LOGS: "TRUE"
      JVM_OPTS: "-Dlog4j.configurationFile=/data/log4j2.xml"
    volumes:
      - minecraft_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  minecraft_data:

networks:
  default:
    name: minecraft-network
